### PR TITLE
Update default project file and instructions

### PR DESCRIPTION
**Pull request by sberrevoets**
Thanks for updating 🙏 

Found a few problems but was able to resolve them pretty easily. Love having this back again!

### CODE REVIEW

**Comment by lautis** [comment]
:+1: for any help text that helps with getting the compilation dome. I'm not sure about the development team / product bundle identifier changes: without this the compilation at least works for me out of the box, but now it works for nobody.

I'm not sure why the product bundle identifier needs to be customisable? Am I missing something?

For development team, I'd hope to be able to use [gitattributes](https://git-scm.com/docs/gitattributes) smudge/clean. This probably could be based on having the empty development team in the project file.

While the same approach could be used for product bundle, is that really needed?

**Comment by sberrevoets** [comment]
> I'm not sure about the development team / product bundle identifier changes: without this the compilation at least works for me out of the box, but now it works for nobody.

Fair point - I figured you might not want your personal details in there but I can see how that makes it harder to iterate. Happy to undo that part.

> I'm not sure why the product bundle identifier needs to be customisable? Am I missing something?

I could be mistaken but I believe a bundle id can only be associated with 1 cert at a time, so anyone but you would have to use that bundle id. Kind of the same as above - if you'd rather keep it in there so this works at least for you I can make that change.

**Comment by lautis** [comment]
That makes sense. I’d like to have a setup where I (or you) can make changes and build the app while having a clean git tree.

**Comment by sberrevoets** [comment]
Yep I understand. I hadn't thought about utilizing gitattributes for that, is there any particular approach you have in mind?

**Comment by lautis** [comment]
Here’s a blog pos explaining the process and usage for a fairly similar case: 
https://www.juandebravo.com/2017/12/02/git-filter-smudge-and-clean/

**Comment by lautis** [comment]
I added the clean and smudge filters and took this in.

**Comment by sberrevoets** [comment]
Awesome, thanks!

**Pull request merged**
